# Ordered Dict

In [1]:
from collections import OrderedDict

In [10]:
ordinary_dictionary = {}
ordinary_dictionary['a'] = 1
ordinary_dictionary['b'] = 2
ordinary_dictionary['c'] = 3
ordinary_dictionary['d'] = 4
ordinary_dictionary['e'] = 5

In [11]:
ordinary_dictionary

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [12]:
ordinary_dictionary['aa'] = 6
ordinary_dictionary

In [34]:
ordered_dictionary = OrderedDict()
ordered_dictionary['a'] = 1
ordered_dictionary['b'] = 2
ordered_dictionary['c'] = 3
ordered_dictionary['d'] = 4
ordered_dictionary['e'] = 5

In [35]:
ordered_dictionary

OrderedDict([('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)])

In [22]:
print(ordered_dictionary)

OrderedDict([('a', 12), ('b', 2), ('c', 3), ('d', 4), ('e', 5), ('aa', 6)])


In [49]:
N = int(input())
ordered_dict = OrderedDict()
for i in range(N):
    items = input().split()
    item_name = ' '.join(items[:-1])
    price = int(items[-1])
    if item_name in ordered_dict.keys():
        ordered_dict[item_name]+=price
    else:
        ordered_dict[item_name] = price

4
candy 5
potato chips 10
candy 5
apple 3


In [50]:
for key, value in ordered_dict.items():
    print(key, value)

candy 10
potato chips 10
apple 3


# Word Order

In [52]:
n = int(input())
ordered_word = OrderedDict()
overall = 0
for i in range(n):
    word = input()
    if word in ordered_word.keys():
        ordered_word[word]+=1
    else:
        ordered_word[word] = 1
        overall +=1
        

4
abc
ghe
bhu
abc


In [53]:
ordered_word

OrderedDict([('abc', 2), ('ghe', 1), ('bhu', 1)])

In [54]:
overall

3

In [58]:
print(overall)
print(*ordered_word.values())

3
2 1 1


# collections deque

In [60]:
from collections import deque

In [61]:
d = deque()
d.append(1)
print(d)

deque([1])


In [85]:
N = int(input())
d = deque()
for i in range(N):
    commands = input().split()
    if commands[0]=='append':
        d.append(commands[1])
    elif commands[0]=='appendleft':
        d.appendleft(commands[1])
    elif commands[0]=='popleft':
        d.popleft()
    else:
        d.pop()
        
    

3
append 1
append 4
pop


In [87]:
print(*d)

1


# incorrect regex

In [3]:
print('correct regex ', '.*\+')
print('incorrect regex ', '.*+')

correct regex  .*\+
incorrect regex  .*+


In [4]:
import re

txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt)

In [6]:
if x:
    print('yes')
else:
    print('no')

yes


In [7]:
x = re.findall("[a-m]", txt)
print(x)

['h', 'e', 'a', 'i', 'i', 'a', 'i']


In [16]:

try: 
    re.compile(".*+")
except re.error:
    print('false')

false
true


In [20]:
def isvalidregex(regex):
    try: 
        re.compile(regex)
    except re.error: 
        return False
    return True

In [24]:
print(isvalidregex('.*|+'))

False


# Concat arrays

In [2]:
import numpy as np

In [46]:
n, m, p =  map(int, input().split())

A = np.array([input().split() for i in range(n)], int)

B = np.array([input().split() for i in range(m)], int)

np.concatenate((A, B), axis=0)

array([[1, 2],
       [3, 4],
       [4, 5],
       [3, 2],
       [4, 6],
       [6, 8],
       [1, 2]])

In [15]:
np.append(A, B, axis=0)

array([[2, 3],
       [3, 4],
       [5, 6],
       [4, 8]])

# Zeros and Ones

In [63]:
f =  list(map(int, input().split()))

print(np.zeros((f), int))
print(np.ones((f), int))

3 2
[[0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]


# itertools.combinations_with_replacement()

In [23]:
from itertools import combinations_with_replacement
from itertools import combinations

# word_list = []
S='HACK'
k = 2
S = list(S)
S.sort()
# print(''.join(S))
for i in list(combinations_with_replacement(S,2)):
    print(''.join(i))

AA
AC
AH
AK
CC
CH
CK
HH
HK
KK


# Linear Algebra

### Task
You are given a square matrix A with dimensions nxn. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.

##### Input Format
The first line contains the integer n.
The next n lines contains the n space separated elements of array A.

##### Output Format

Print the determinant of A.

In [2]:
import numpy as np
# numpy.array([input().split() for _ in range(int(input()))],float)

In [8]:

n = int(input())
print(round(np.linalg.det(np.array([input().split() for i in range(n)], float)),2))


 2
 1.1 1.1
 1.1 1.1


0.0


# Transpose and Flatten

### Task

You are given a N X M integer array matrix with space separated elements (N = rows and M = columns).
Your task is to print the transpose and flatten results.

##### Input Format

The first line contains the space separated values of N and M.
The next N lines contains the space separated elements of M columns.

##### Output Format

First, print the transpose array and then print the flatten.

In [11]:
n, m =  map(int, input().split())

A = np.array([input().split() for i in range(n)], float)
print(np.transpose(A))
print(A.flatten())


 2 2
  2 4
 3 5


[[2. 3.]
 [4. 5.]]
[2. 4. 3. 5.]


# Eye and Identity

In [18]:
import numpy as np 
np.set_printoptions(legacy='1.13')

In [19]:
np.eye(8,7,-1)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
n, m =  map(int, input().split())

A = np.eye(n,m)

 3 3


In [21]:
A

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# Compress the String!

In [2]:
from itertools import groupby

In [32]:
# round(100/22,0)
x = 9
print(x*2**2) 


36


In [63]:
s = '1222311'

out1 = []
for k, g in groupby(s):
    size = len(list(g))
    out1.append((size, int(k)))

print(*out1)   

(1, 1) (3, 2) (1, 3) (2, 1)


# collections.Counter()